/**
 * Every user-facing string, in one place.
 *
 * The engine is English-only by decision — its user administers a box, and its
 * vocabulary is Docker, versions and backups. This module is the one cheap
 * precaution that decision requires: nothing user-facing is written inline in
 * JSX, so if a firm ever asks for Arabic it is a week of translating this
 * file, not a month of hunting through components.
 */
export const S = {
  productName: 'QanoonTech',
  engineWord: 'Engine',

  // Sign-in
  loginTitle: 'Sign in',
  loginExplainer: 'The operations panel for this deployment. Sign in with the Microsoft account this deployment permits.',
  loginFootnote: 'Sign-ins are recorded in the activity trail.',
  loginSubmit: 'Sign in with Microsoft',
  logout: 'Sign out',
  loginTagline: 'The operations panel for one firm’s deployment: whether it is safe, and every change to it.',
  operatorLabel: 'Operator',
  signedInViaEntra: 'Signed in with Microsoft',

  // Navigation
  groupAssurance: 'Assurance',
  groupChange: 'Change',
  groupRecovery: 'Recovery',
  navOverview: 'Overview',
  navServices: 'Services',
  navActivity: 'Activity',
  navDeploy: 'Deploy',
  navBackups: 'Backups',
  navSettings: 'Settings',
  sidebarCollapse: 'Collapse',
  sidebarExpand: 'Expand',

  // Overview
  overviewChecked: (ago: string, address: string, port: number) => `Checked ${ago} · serving on ${address}:${port}`,
  verdictProtected: 'Protected.',
  verdictAttention: 'Needs attention.',
  verdictRisk: 'At risk.',
  verdictNothing: 'Every responsibility is met.',
  verdictCount: (risks: number, warns: number) =>
    [risks > 0 ? `${risks} at risk` : '', warns > 0 ? `${warns} to look at` : ''].filter(Boolean).join(' · '),
  factApplication: 'Application',
  factBackups: 'Newest backup',
  factOffsite: 'Offsite copy',
  factRecovery: 'Engine snapshot',
  factDrift: (configured: string) => `${configured} is configured — deploy to apply`,
  factServicesOk: (count: number) => `${count} services running`,
  factServicesDown: 'A required service is not running',
  factBackupsCaption: (next: string, sets: number) => `Next ${next} · ${sets} kept`,
  factOffsiteOffCaption: 'Every copy is on this box',
  factOffsitePending: (n: number) => `${n} not yet copied`,
  factOffsiteCurrent: 'Every set is copied',
  factRecoveryCaption: 'Encrypted state in the bucket',
  factRecoveryVerified: (ago: string) => `Confirmed in the bucket ${ago}`,
  factRecoveryNoPassphrase: 'Engine state is not copied offsite',
  notRunning: 'Not running',
  never: 'Never',
  notYet: 'Not yet',
  noPassphrase: 'No passphrase',
  offsiteOn: 'On',
  offsiteOff: 'Off',
  offsiteNotUsable: 'Not usable',
  attentionTitle: 'Needs attention',
  attentionExplainer: 'In the order to deal with them. Each opens the page that fixes it.',
  activityTitle: 'Recent activity',
  activityExplainer: 'Sign-ins, changes and failures. Routine work — hourly backups, offsite copies — is under Activity.',
  activityAll: 'All activity',
  auditEmpty: 'Nothing yet.',
  dockerUnreachable: 'Docker did not answer:',

  // Activity
  activityPageExplainer: 'Everything the engine has recorded, newest first. Sign-ins and changes carry who did them.',
  filterNotable: 'Notable',
  filterAll: 'All',
  activityOlder: 'Older',
  auditKind: {
    security: 'Sign-in',
    change: 'Change',
    failure: 'Failure',
    routine: 'Routine',
  } as const,

  // Services
  servicesExplainer: 'What the deployment runs, and the state Docker reports for each. The database is asked directly when it lives elsewhere.',
  requiredBadge: 'required',
  actionStart: 'Start',
  actionStop: 'Stop',
  actionRestart: 'Restart',
  actionLogs: 'Logs',
  serviceVerbDone: { start: 'Started', stop: 'Stopped', restart: 'Restarted' } as const,
  stopDialogTitle: (service: string) => `Stop ${service}?`,
  stopDialogBody: 'The firm loses access to the system until it is started again. Nothing is lost; nothing is reachable.',
  logsTitle: (service: string) => `${service} — logs`,
  logsRecent: (lines: number) => `The most recent ${lines} lines.`,
  logsEmpty: 'No output.',
  logsWrap: 'Wrap',
  logsFollow: 'Follow',
  logsCopy: 'Copy',
  logsCopied: 'Copied',
  serviceColumn: 'Service',
  stateColumn: 'State',
  detailColumn: 'Detail',
  actionsColumn: '',
  close: 'Close',

  // Deploy
  deployTitle: 'Deploy',
  deployPageExplainer: 'What version and modules the deployment runs, and how it gets there.',
  registryTitle: 'Registry credential',
  registryExplainer: 'Issued per firm, with read:packages only. It is how the software is downloaded.',
  registryUsername: 'Username',
  registryToken: 'Token',
  registryConfigured: (username: string) => `Downloads as ${username}.`,
  registryChange: 'Change',
  registrySave: 'Verify and save',
  settingsTitle: 'Configuration',
  settingsExplainer: 'The deployment’s own settings. They take effect on the next deploy.',
  settingsBindAddress: 'Serve on address',
  settingsBindAddressHint:
    '0.0.0.0 serves the whole LAN (the default). Narrow it to 127.0.0.1 or a specific address when fronting with the Cloudflare tunnel.',
  settingsAppPort: 'Application port',
  settingsTimezone: 'Timezone',
  settingsLanguage: 'Default language',
  settingsSave: 'Save',
  settingsSaved: 'Saved.',
  modulesTitle: 'Modules',
  modulesExplainer: 'Optional, off by default, and the cost is stated.',
  moduleEnable: 'Enable',
  moduleDisable: 'Disable',
  moduleConfigure: 'Configure',
  moduleConfigSave: 'Save configuration',
  moduleConfigSaved: 'Saved.',
  moduleResources: 'Resources',
  moduleMemory: 'Memory limit',
  moduleCpus: 'CPU limit',
  moduleResourceHint: (mem: string, cpus: string) =>
    `Default ${mem} memory, ${cpus} CPU. Raise these on a larger box, where a module has room to use more.`,
  moduleOn: 'on',
  moduleOff: 'off',
  secretSet: 'set',
  secretOptional: 'optional',
  secretReplacePlaceholder: 'Already set — enter a value to replace it',
  secretChooseFile: 'Choose file…',
  versionTitle: 'Version',
  versionRunning: 'Running',
  versionCurrent: 'Configured',
  versionPrevious: 'Previous',
  versionNotDeployed: 'not yet deployed',
  versionChoose: 'Choose a version',
  versionSet: 'Set version',
  versionRollback: 'Roll back',
  rollbackBody: 'The previous image is put back and deployed; the configuration is otherwise unchanged.',
  versionRollbackWarn:
    'The application migrates its database forward on start; an older version may refuse a newer database. The pre-update backup is the way back.',
  preflightTitle: 'Checks',
  preflightExplainer: 'What a deploy would find before it touches anything.',
  preflightRun: 'Run checks',
  preflightBlocked: 'Blocked — fix the failures above before deploying.',
  deployRunTitle: 'Deploy',
  deployExplainer:
    'Renders the deployment, checks it, takes a backup, downloads images, then applies. A failed download touches nothing that is running.',
  deployStart: 'Deploy now',
  deployRunning: 'Deploying…',
  deployRunningVersion: (from: string, to: string) => `Running ${from} · deploying ${to}`,
  imgWaiting: 'waiting',
  imgDownloading: 'downloading',
  imgExtracting: 'unpacking',
  imgStalled: 'stalled — retrying',
  imgDone: 'done',
  imgFailed: 'failed',
  deployDone: 'Deployed.',
  deployFailed: 'Deploy failed — the log has the reason.',
  deployConfirmBody: 'A pre-update backup is taken first, and a failed download touches nothing that is running. Roll back is available afterwards.',

  // Backups
  backupsPageExplainer:
    'The database hourly and every document daily, kept here for thirty days; a copy of each in the bucket; the engine’s own state encrypted beside them.',
  backupTakeNow: 'Back up now',
  backupTaking: 'Backing up…',
  backupRestore: 'Restore',
  backupDelete: 'Delete',
  backupCopyOffsite: 'Copy offsite now',
  backupRestoreConfirm: (id: string) =>
    `Restore ${id}? The application stops during the restore. A safety copy of the current state is taken first, so this is reversible.`,
  backupDeleteConfirm: (id: string) => `Delete ${id} from this box? A copy in the bucket, if there is one, is untouched.`,
  backupEmpty: 'No backups yet.',
  backupTrigger: {
    manual: 'manual',
    hourly: 'hourly',
    daily: 'daily',
    'pre-update': 'before update',
    'pre-restore': 'before restore',
  } as Record<string, string>,
  setsTitle: 'Sets on this box',
  nextDue: 'Next due',
  everyInterval: 'Hourly; documents daily',
  kept: 'Kept',
  keptCaption: 'Thirty days, then pruned',
  restoreStepsTitle: 'Restore steps',
  offsiteTitle: 'Offsite copy',
  offsiteExplainer: 'Every set is copied to the bucket after it is taken, and the bucket is asked whether it still holds them.',
  offsiteSent: 'copied',
  offsitePending: 'not yet copied',
  offsiteError: 'copy failing',
  offsiteNotConfigured: 'Offsite storage is not configured. Set it up from the shell with `offsite use-s3`; the panel gains it in the next release.',
  offsiteRemoteTitle: 'In the bucket',
  offsiteRemoteExplainer: 'What the bucket holds. Bringing a set back puts it in the list above, where it restores like any other.',
  offsiteRemoteLoad: 'Look in the bucket',
  offsiteBringBack: 'Bring back',
  offsiteLocalToo: 'also here',
  backupColumnSet: 'Set',
  backupColumnKind: 'Kind',
  backupColumnContents: 'Contents',
  backupRestoreDialogTitle: 'Restore this backup?',
  backupDeleteDialogTitle: 'Delete this backup?',
  databaseWord: 'database',
  documentsWord: 'documents',
  cancel: 'Cancel',
  supportTitle: 'Support bundle',
  supportExplainer:
    'A redacted snapshot of this deployment — states, logs, configuration — for sending to support. No documents, no database rows, no secrets. Nothing is sent anywhere; you download it and decide.',
  supportDownload: 'Download support bundle',

  // Settings
  settingsPageExplainer: 'The engine itself. Sign-in, the database and credentials are configured from the shell until the next release.',
  engineTitle: 'Engine',
  engineExplainer: 'The panel itself. Updating it restarts this page for a few seconds; the firm’s system is not touched.',
  engineRunning: 'Running version',
  engineChoose: 'Update to',
  engineUpdate: 'Update engine',
  engineUpdateDialogTitle: 'Update the engine?',
  engineUpdateDialogBody: (from: string, to: string) =>
    `The panel will restart on version ${to} (from ${from}). The application keeps running untouched, and you will still be signed in. Stay on this page — it will report when the new engine answers.`,
  engineUpdating: 'Updating… the panel is restarting.',
  engineUpdated: (version: string) => `The engine is now on ${version}.`,
  engineUpdateStuck: (version: string) =>
    `Still on ${version} — the update may have failed to pull. The old engine is untouched; check the box's Docker logs.`,

  // Toasts
  toastBackupTaken: 'Backup taken and verified.',
  toastDeployDone: 'Deployed.',
  toastServiceDone: (verb: string, service: string) => `${verb} ${service}.`,

  // Errors
  errorGeneric: 'Something went wrong. The details are in the engine log.',
  workingEllipsis: 'Working…',
} as const
