/**
 * Every user-facing string, in one place.
 *
 * The engine is English-only by decision — its user administers a box, and its
 * vocabulary is Docker, versions and backups. This module is the one cheap
 * precaution that decision requires: nothing user-facing is written inline in
 * JSX, so if a firm ever asks for Arabic it is a week of translating this
 * file, not a month of hunting through components.
 */
export const S = {
  productName: 'QanoonTech',
  engineWord: 'Engine',

  // Sign-in
  loginTitle: 'Sign in',
  loginExplainer: 'The operations panel for this deployment. Sign in with the Microsoft account this deployment permits.',
  loginFootnote: 'Sign-ins are recorded in the activity trail.',
  loginSubmit: 'Sign in with Microsoft',
  logout: 'Sign out',
  loginTagline: 'The operations panel for one firm’s deployment: whether it is safe, and every change to it.',
  operatorLabel: 'Operator',
  signedInViaEntra: 'Signed in with Microsoft',

  // Navigation
  groupAssurance: 'Assurance',
  groupChange: 'Change',
  groupRecovery: 'Recovery',
  navOverview: 'Overview',
  navServices: 'Services',
  navActivity: 'Activity',
  navDeploy: 'Deploy',
  navBackups: 'Backups',
  navSettings: 'Settings',
  sidebarCollapse: 'Collapse',
  sidebarExpand: 'Expand',

  // Overview
  overviewChecked: (ago: string, address: string, port: number) => `Checked ${ago} · serving on ${address}:${port}`,
  verdictProtected: 'Protected.',
  verdictAttention: 'Needs attention.',
  verdictRisk: 'At risk.',
  verdictNothing: 'Every responsibility is met.',
  verdictCount: (risks: number, warns: number) =>
    [risks > 0 ? `${risks} at risk` : '', warns > 0 ? `${warns} to look at` : ''].filter(Boolean).join(' · '),
  factApplication: 'Application',
  factBackups: 'Newest backup',
  factOffsite: 'Offsite copy',
  factRecovery: 'Engine snapshot',
  factDrift: (configured: string) => `${configured} is configured — deploy to apply`,
  factServicesOk: (count: number) => `${count} services running`,
  factServicesDown: 'A required service is not running',
  factBackupsCaption: (next: string, sets: number) => `Next ${next} · ${sets} kept`,
  factOffsiteOffCaption: 'Every copy is on this box',
  factOffsitePending: (n: number) => `${n} not yet copied`,
  factOffsiteCurrent: 'Every set is copied',
  factRecoveryCaption: 'Encrypted state in the bucket',
  factRecoveryVerified: (ago: string) => `Confirmed in the bucket ${ago}`,
  factRecoveryNoPassphrase: 'Engine state is not copied offsite',
  notRunning: 'Not running',
  never: 'Never',
  notYet: 'Not yet',
  noPassphrase: 'No passphrase',
  offsiteOn: 'On',
  offsiteOff: 'Off',
  offsiteNotUsable: 'Not usable',
  attentionTitle: 'Needs attention',
  attentionExplainer: 'In the order to deal with them. Each opens the page that fixes it.',
  activityTitle: 'Recent activity',
  activityExplainer: 'Sign-ins, changes and failures. Routine work — hourly backups, offsite copies — is under Activity.',
  activityAll: 'All activity',
  auditEmpty: 'Nothing yet.',
  dockerUnreachable: 'Docker did not answer:',

  // Activity
  activityPageExplainer: 'Everything the engine has recorded, newest first. Sign-ins and changes carry who did them.',
  filterNotable: 'Notable',
  filterAll: 'All',
  activityOlder: 'Older',
  auditKind: {
    security: 'Sign-in',
    change: 'Change',
    failure: 'Failure',
    routine: 'Routine',
  } as const,

  // Services
  servicesExplainer: 'What the deployment runs, and the state Docker reports for each. The database is asked directly when it lives elsewhere.',
  requiredBadge: 'required',
  actionStart: 'Start',
  actionStop: 'Stop',
  actionRestart: 'Restart',
  actionLogs: 'Logs',
  serviceVerbDone: { start: 'Started', stop: 'Stopped', restart: 'Restarted' } as const,
  stopDialogTitle: (service: string) => `Stop ${service}?`,
  stopDialogBody: 'The firm loses access to the system until it is started again. Nothing is lost; nothing is reachable.',
  logsTitle: (service: string) => `${service} — logs`,
  logsRecent: (lines: number) => `The most recent ${lines} lines.`,
  logsEmpty: 'No output.',
  logsWrap: 'Wrap',
  logsFollow: 'Follow',
  logsCopy: 'Copy',
  logsCopied: 'Copied',
  serviceColumn: 'Service',
  stateColumn: 'State',
  detailColumn: 'Detail',
  actionsColumn: '',
  close: 'Close',

  // Deploy
  deployTitle: 'Deploy',
  deployPageExplainer: 'What version and modules the deployment runs, and how it gets there.',
  registryTitle: 'Registry credential',
  registryExplainer: 'Issued per firm, with read:packages only. It is how the software is downloaded.',
  registryUsername: 'Username',
  registryToken: 'Token',
  registryConfigured: (username: string) => `Downloads as ${username}.`,
  registryChange: 'Change',
  registrySave: 'Verify and save',
  settingsTitle: 'Configuration',
  settingsExplainer: 'The deployment’s own settings. They take effect on the next deploy.',
  settingsBindAddress: 'Serve on address',
  settingsBindAddressHint:
    '0.0.0.0 serves the whole LAN (the default). Narrow it to 127.0.0.1 or a specific address when fronting with the Cloudflare tunnel.',
  settingsAppPort: 'Application port',
  settingsTimezone: 'Timezone',
  settingsLanguage: 'Default language',
  settingsSave: 'Save',
  settingsSaved: 'Saved.',
  modulesTitle: 'Modules',
  modulesExplainer: 'Optional, off by default, and the cost is stated.',
  moduleEnable: 'Enable',
  moduleDisable: 'Disable',
  moduleConfigure: 'Configure',
  moduleConfigSave: 'Save configuration',
  moduleConfigSaved: 'Saved.',
  moduleResources: 'Resources',
  moduleMemory: 'Memory limit',
  moduleCpus: 'CPU limit',
  moduleResourceHint: (mem: string, cpus: string) =>
    `Default ${mem} memory, ${cpus} CPU. Raise these on a larger box, where a module has room to use more.`,
  moduleOn: 'on',
  moduleOff: 'off',
  secretSet: 'set',
  secretOptional: 'optional',
  secretReplacePlaceholder: 'Already set — enter a value to replace it',
  secretChooseFile: 'Choose file…',
  versionTitle: 'Version',
  versionRunning: 'Running',
  versionCurrent: 'Configured',
  versionPrevious: 'Previous',
  versionNotDeployed: 'not yet deployed',
  versionChoose: 'Choose a version',
  versionSet: 'Set version',
  versionRollback: 'Roll back',
  rollbackBody: 'The previous image is put back and deployed; the configuration is otherwise unchanged.',
  versionRollbackWarn:
    'The application migrates its database forward on start; an older version may refuse a newer database. The pre-update backup is the way back.',
  preflightTitle: 'Checks',
  preflightExplainer: 'What a deploy would find before it touches anything.',
  preflightRun: 'Run checks',
  preflightBlocked: 'Blocked — fix the failures above before deploying.',
  deployRunTitle: 'Deploy',
  deployExplainer:
    'Renders the deployment, checks it, takes a backup, downloads images, then applies. A failed download touches nothing that is running.',
  deployStart: 'Deploy now',
  deployRunning: 'Deploying…',
  deployRunningVersion: (from: string, to: string) => `Running ${from} · deploying ${to}`,
  imgWaiting: 'waiting',
  imgDownloading: 'downloading',
  imgExtracting: 'unpacking',
  imgStalled: 'stalled — retrying',
  imgDone: 'done',
  imgFailed: 'failed',
  deployDone: 'Deployed.',
  deployFailed: 'Deploy failed — the log has the reason.',
  deployConfirmBody: 'A pre-update backup is taken first, and a failed download touches nothing that is running. Roll back is available afterwards.',

  // Backups
  backupsPageExplainer:
    'The database hourly and every document daily, kept here for thirty days; a copy of each in the bucket; the engine’s own state encrypted beside them.',
  backupTakeNow: 'Back up now',
  backupTaking: 'Backing up…',
  backupRestore: 'Restore',
  backupDelete: 'Delete',
  backupCopyOffsite: 'Copy offsite now',
  backupRestoreConfirm: (id: string) =>
    `Restore ${id}? The application stops during the restore. A safety copy of the current state is taken first, so this is reversible.`,
  backupDeleteConfirm: (id: string) => `Delete ${id} from this box? A copy in the bucket, if there is one, is untouched.`,
  backupEmpty: 'No backups yet.',
  backupTrigger: {
    manual: 'manual',
    hourly: 'hourly',
    daily: 'daily',
    'pre-update': 'before update',
    'pre-restore': 'before restore',
  } as Record<string, string>,
  setsTitle: 'Sets on this box',
  backupsVerified: 'Taken and verified',
  nextDue: 'Next due',
  everyInterval: 'Hourly; documents daily',
  kept: 'Kept',
  keptCaption: 'Thirty days, then pruned',
  restoreStepsTitle: 'Restore steps',
  tabSets: 'Sets',
  tabOffsite: 'Offsite',
  tabSchedule: 'Schedule',
  tabRecovery: 'Recovery',
  setsExplainer: 'Newest first. Restoring stops the application for the length of the restore and takes a safety copy first.',
  offsiteWhereTitle: 'Where the copies go',
  offsiteWhereExplainer: 'S3-compatible object storage the firm controls — Cloudflare R2. The keys are written once and never shown again.',
  offsiteEnable: 'Copy every backup to the bucket',
  offsiteEndpoint: 'Endpoint',
  offsiteEndpointHelp: 'The account’s S3 endpoint, https, no path.',
  offsiteBucket: 'Bucket',
  offsiteBucketHelp: 'One bucket per firm. A lifecycle rule on the backups/ prefix keeps it to thirty days.',
  offsiteRegion: 'Region',
  offsiteRegionHelp: 'The credential scope. R2 wants "auto".',
  offsitePrefix: 'Prefix',
  offsitePrefixHelp: 'Optional. Lets one bucket hold several deployments.',
  offsiteAccessKey: 'Access key ID',
  offsiteSecretKey: 'Secret access key',
  offsiteKeysHelp: 'An R2 API token with object read and write on this bucket only.',
  offsiteTest: 'Test the bucket',
  offsiteTestOk: (label: string) => `${label} is writable and readable from this box.`,
  offsiteTestFailed: 'Do not trust this store until the failure above is fixed.',
  offsiteHereSummary: (sets: number, pending: number) => `${sets} set${sets === 1 ? '' : 's'} on this box, ${pending} not yet copied.`,
  offsiteDocumentsSummary: (files: number, size: string) => `${files} document${files === 1 ? '' : 's'} in the bucket, ${size}.`,
  scheduleTitle: 'When, and for how long',
  scheduleExplainer: 'The database is small and cheap to copy; documents are the slow half and change rarely, so they ride the daily set.',
  scheduleInterval: 'Database interval, minutes',
  scheduleIntervalHelp: 'Hourly by default. On a firm’s box a compressed dump is about 140 KB and takes 160 ms; the floor is five minutes.',
  scheduleHour: 'Daily set, with documents, at',
  scheduleHourHelp: (tz: string) => `Read in ${tz}. Two in the morning by default, when nobody is filing.`,
  scheduleRetention: 'Keep sets for, days',
  scheduleRetentionHelp: 'Hourly sets for two days, then one a day for this long. Match the bucket’s lifecycle rule.',
  scheduleDocuments: 'Documents on this box',
  scheduleDocumentsHelp: 'Where documents are already copied offsite one by one, the local daily set can be the database alone.',
  scheduleDocumentsLabel: 'Include documents in the daily set',
  snapshotTitle: 'Engine snapshot',
  snapshotExplainer: 'The engine’s own state — settings, credentials, the audit tail — encrypted with the passphrase and kept beside the backups. It is what turns a restored database back into a deployment.',
  snapshotPassphrase: 'Passphrase',
  snapshotCopied: 'Last copied',
  snapshotInStore: 'In the bucket',
  notSet: 'Not set',
  unknown: 'Unknown',
  yes: 'Yes',
  no: 'No',
  passphraseSetLabel: 'Set the passphrase',
  passphraseReplace: 'Replace the passphrase',
  passphraseAgain: 'Once more',
  passphraseHelp: 'Twelve characters at least. Write it down somewhere that survives this machine.',
  passphraseWarning: 'Lose it and the snapshot cannot be opened by anyone, including you. Replacing it re-seals the snapshot on the next tick; the copy already in the bucket opens with the previous one until then.',
  passphraseMismatch: 'The two entries differ.',
  passphraseSetToast: 'Recovery passphrase set.',
  passphraseReplaced: 'Recovery passphrase replaced.',
  drillTitle: 'Prove a backup restores',
  drillExplainer: 'Restores the newest set into a scratch database, times it, counts the tables and rows, and throws the copy away. The live database is not touched.',
  drillRun: 'Run a drill',
  drillNever: 'No drill has been run yet.',
  drillTime: 'Restore time',
  drillTimeCaption: 'The database alone; documents restore separately',
  drillTables: 'Tables',
  drillRows: 'Rows',
  recoveryNeedsTitle: 'What a bare machine needs',
  recoveryNeedsExplainer: 'Read this before the day it matters. Everything else comes back from the bucket.',
  recoveryNeeds: ['The bucket’s endpoint', 'The bucket’s name', 'The access key ID and secret access key', 'The recovery passphrase'] as readonly string[],
  recoveryCommand: 'docker run --rm -it -v /var/run/docker.sock:/var/run/docker.sock -v qanoontech_engine:/var/lib/qanoontech-engine \\\n  ghcr.io/alikhubrani/qanoontech-engine node dist/cli.js recovery run --endpoint <endpoint> --bucket <bucket>',
  offsiteTitle: 'Offsite copy',
  offsiteExplainer: 'Every set is copied to the bucket after it is taken, and the bucket is asked whether it still holds them.',
  offsiteSent: 'copied',
  offsitePending: 'not yet copied',
  offsiteError: 'copy failing',
  offsiteNotConfigured: 'Offsite storage is not configured. Set it up from the shell with `offsite use-s3`; the panel gains it in the next release.',
  offsiteRemoteTitle: 'In the bucket',
  offsiteRemoteExplainer: 'What the bucket holds. Bringing a set back puts it in the list above, where it restores like any other.',
  offsiteRemoteLoad: 'Look in the bucket',
  offsiteBringBack: 'Bring back',
  offsiteLocalToo: 'also here',
  backupColumnSet: 'Set',
  backupColumnKind: 'Kind',
  backupColumnContents: 'Contents',
  backupRestoreDialogTitle: 'Restore this backup?',
  backupDeleteDialogTitle: 'Delete this backup?',
  databaseWord: 'database',
  documentsWord: 'documents',
  cancel: 'Cancel',
  supportTitle: 'Support bundle',
  supportExplainer:
    'A redacted snapshot of this deployment — states, logs, configuration — for sending to support. No documents, no database rows, no secrets. Nothing is sent anywhere; you download it and decide.',
  supportDownload: 'Download support bundle',

  // Settings
  settingsPageExplainer: 'Who may sign in, where the database is, the credentials, the alert address, and the engine itself.',
  tabSignIn: 'Sign-in',
  tabDatabase: 'Database',
  tabRegistry: 'Registry',
  tabCredentials: 'Credentials',
  tabAlerts: 'Alerts',
  tabEngine: 'Engine',
  tabRelease: 'Release',
  tabModules: 'Modules',
  tabConfiguration: 'Configuration',
  authTitle: 'Microsoft Entra',
  authExplainer: 'Identity is Microsoft’s. The panel has no password; it decides only which accounts of the tenant it admits, by object id.',
  authTenant: 'Tenant',
  authClient: 'Application',
  authSecret: 'Client secret',
  authRedirect: 'Redirect URI',
  authRedirectHelp: 'Must match the one registered on the Entra application exactly, https. The panel also answers only to this host name; a change takes effect when the engine restarts.',
  authAllowed: 'Allowed accounts',
  authAllowedHelp: (me: string) => `Object ids, one per line. Your own account (${me}) must stay on the list; the server refuses a save that would remove it.`,
  authAllowedNoSubject: 'This session predates the check that keeps you on the list. Sign out and in again before changing it.',
  authClientSecret: 'Client secret',
  authClientSecretHelp: 'From the application’s Certificates & secrets. Note its expiry: when it lapses nobody can sign in, and the shell is the way back.',
  authSavedRestart: 'Saved. The engine must restart before it answers to the new host name.',
  signOutEveryoneTitle: 'Sign out everyone',
  signOutEveryoneExplainer: 'The engine’s half of revoking access. Entra stops new sign-ins the moment an account is disabled; sessions already issued are cookies on laptops, and this is what ends them.',
  signOutEveryone: 'Sign out everyone',
  signOutEveryoneNote: 'You are signed out too, and land on the sign-in page.',
  signOutEveryoneConfirm: 'Every session on this box ends now, including this one. Entra decides who may start a new one.',
  databaseTitle: 'Where the database is',
  databaseExplainer: 'The application’s PostgreSQL: the postgres module in this deployment, or a server elsewhere reached by a connection string. Asked directly, just now.',
  databaseAsking: 'Asking the database…',
  databaseWhere: 'Where',
  databaseExternal: 'External',
  databaseLocal: 'This deployment',
  databaseServer: 'Server',
  databaseUnreachable: 'Not answering',
  databaseTables: 'Tables',
  databaseUser: 'Role',
  databaseSwitchTitle: 'Use a database elsewhere',
  databaseSwitchExplainer: 'The URL is proven before it is stored: it answers, its sslmode matches what the server offers, and the role can create the drill’s scratch database. The application moves on the next deploy.',
  databaseUrl: 'Connection string',
  databaseUrlHelp: 'postgresql://user:password@host:port/database?sslmode=… Stored as a credential, never shown again.',
  databaseTest: 'Test',
  databaseUse: 'Use this database',
  databaseUseLocal: 'Back to the local database',
  databaseSwitched: 'Saved. Deploy to move the application.',
  databaseSwitchNote: 'Switching does not move data. A database with no schema is migrated on the next deploy and the firm sees an empty system; a backup restores into whichever database is current.',
  databaseUseConfirm: 'The postgres module will not be rendered. Deploy afterwards to move the application over; the local volume is kept, and the local database is one click back.',
  databaseUseLocalConfirm: 'The postgres module is rendered again on the next deploy. Whatever was written to the external database since the switch is not in the local volume.',
  credentialsTitle: 'Every credential by name',
  credentialsExplainer: 'Set or not, and what uses each. Values are written and never read back. Removing one the deployment still uses is refused unless you insist.',
  credentialsEmpty: 'Nothing stored.',
  secretGenerated: 'generated',
  secretUsedBy: (by: string) => `Used by ${by}`,
  secretUnused: 'Nothing uses it',
  secretSetAction: 'Set',
  secretReplace: 'Replace',
  secretRemove: 'Remove',
  secretRemoveAnyway: 'Remove anyway',
  secretValue: 'Value',
  secretValueHelp: 'Pasted once. Leading and trailing spaces are kept as typed.',
  secretStored: (name: string) => `${name} stored.`,
  secretRemoved: (name: string) => `${name} removed.`,
  secretRemoveTitle: (name: string) => `Remove ${name}?`,
  secretRemoveBody: 'Nothing running uses it.',
  secretRemoveInUse: (by: string) => `It is used by ${by}. Removing it breaks that until it is set again.`,
  secretRemoveSnapshotNote: 'The offsite snapshot still carries it until the next tick rewrites it.',
  alertsTitle: 'When backups stop',
  alertsExplainer: 'One email when the backup system changes state, sent by the engine itself over SMTP, so it goes out when the application cannot. Repeated every six hours while the problem stands.',
  alertsEmail: 'Send to',
  alertsEmailHelp: 'Uses the SMTP settings of the email module.',
  alertsLast: (level: string, at: string, ago: string) => `Last alert: backups ${level}, ${at} (${ago}).`,
  alertsNever: 'No alert has been sent.',
  engineTitle: 'Engine',
  engineExplainer: 'The panel itself. Updating it restarts this page for a few seconds; the firm’s system is not touched.',
  engineRunning: 'Running version',
  engineChoose: 'Update to',
  engineUpdate: 'Update engine',
  engineUpdateDialogTitle: 'Update the engine?',
  engineUpdateDialogBody: (from: string, to: string) =>
    `The panel will restart on version ${to} (from ${from}). The application keeps running untouched, and you will still be signed in. Stay on this page — it will report when the new engine answers.`,
  engineUpdating: 'Updating… the panel is restarting.',
  engineUpdated: (version: string) => `The engine is now on ${version}.`,
  engineUpdateStuck: (version: string) =>
    `Still on ${version} — the update may have failed to pull. The old engine is untouched; check the box's Docker logs.`,

  // Toasts
  toastBackupTaken: 'Backup taken and verified.',
  toastDeployDone: 'Deployed.',
  toastServiceDone: (verb: string, service: string) => `${verb} ${service}.`,

  // Errors
  errorGeneric: 'Something went wrong. The details are in the engine log.',
  workingEllipsis: 'Working…',
} as const
