import { stringify } from 'yaml'
import type {
  AnyModule,
  DeploymentSettings,
  HealthCheck,
  RenderedService,
  ResolvedModule,
} from '../catalogue/index.js'

export const PROJECT_NAME = 'qanoontech'
export const NETWORK_NAME = 'internal'

export interface RenderInput {
  readonly modules: readonly ResolvedModule[]
  readonly version: string
  readonly settings: DeploymentSettings
  /** Secret values by name, from the engine's own store. */
  readonly secrets: Readonly<Record<string, string>>
  /** Per-module resource overrides; falls back to each module's catalogue cost. */
  readonly resources?: Readonly<Record<string, { memory?: string | undefined; cpus?: string | undefined }>>
}

export interface RenderProblem {
  readonly moduleId?: string
  readonly message: string
}

export type RenderResult =
  | { readonly ok: true; readonly yaml: string }
  | { readonly ok: false; readonly problems: readonly RenderProblem[] }

const HEADER = `# Generated by the QanoonTech engine. Do not edit.
#
# Edits here are lost the next time anything changes, because this file is
# rendered from the engine's module catalogue and its stored configuration —
# it is an output, not a source.
#
# It is written to disk on purpose, and it is the reason the engine renders
# compose rather than driving the Docker API directly: when the engine will not
# start, this file is what still explains the deployment, and it can be brought
# up by hand with 'docker compose up -d'.
`

/**
 * Render the resolved modules to a compose file.
 *
 * Nothing about a deployment is decided here — resolution already settled what
 * runs. This turns that into the file, and refuses one thing it will not emit
 * whatever it is asked: a module wanting a secret nobody has supplied.
 *
 * A wildcard bind address is allowed on purpose (decided 2026-09-02):
 * deployments serve their LAN by default, and a firm that fronts the system
 * with a Cloudflare tunnel narrows the address then, deliberately, in
 * settings — reachability is a configuration, not a refusal.
 */
export function render(input: RenderInput): RenderResult {
  const problems: RenderProblem[] = []

  if (input.version.trim() === '') {
    problems.push({ message: 'No version chosen. Nothing can be rendered without one.' })
  }

  const services: Record<string, unknown> = {}
  const renderedByModule = new Map<string, { module: AnyModule; rendered: RenderedService }>()
  const volumes = new Set<string>()
  let anyHostNetwork = false

  for (const { module, config } of input.modules) {
    const requested = new Set<string>()
    const secret = (name: string): string => {
      requested.add(name)
      const value = input.secrets[name]
      if (value === undefined || value === '') {
        throw new MissingSecret(name)
      }
      return value
    }

    let rendered: RenderedService
    try {
      rendered = module.render({
        version: input.version,
        settings: input.settings,
        config: config as never,
        secret,
        isEnabled: (id) => input.modules.some((m) => m.module.id === id),
      })
    } catch (error) {
      if (error instanceof MissingSecret) {
        problems.push({
          moduleId: module.id,
          message: `'${module.title}' needs the secret ${error.secretName}, which is not set.`,
        })
        continue
      }
      throw error
    }

    if (rendered.hostNetwork) anyHostNetwork = true
    for (const name of module.volumes) volumes.add(name)

    renderedByModule.set(module.id, { module, rendered })
  }

  if (problems.length > 0) return { ok: false, problems }

  for (const { module, rendered } of renderedByModule.values()) {
    services[module.id] = composeService(module, rendered, renderedByModule, input.resources?.[module.id])
  }

  const document: Record<string, unknown> = {
    name: PROJECT_NAME,
    services,
  }

  // A host-networked service belongs to no compose network, so a deployment
  // that is only the tunnel would declare a network nothing joins.
  if (Object.keys(services).length > (anyHostNetwork ? 1 : 0)) {
    document['networks'] = {
      // No fixed subnet: a hardcoded block collides with whatever else the host
      // runs, and nothing here needs a predictable address — services find each
      // other by name.
      [NETWORK_NAME]: { driver: 'bridge' },
    }
  }

  if (volumes.size > 0) {
    document['volumes'] = Object.fromEntries([...volumes].sort().map((name) => [name, null]))
  }

  return { ok: true, yaml: HEADER + '\n' + stringify(document, { lineWidth: 0 }) }
}

class MissingSecret extends Error {
  constructor(readonly secretName: string) {
    super(`Missing secret: ${secretName}`)
  }
}

function composeService(
  module: AnyModule,
  rendered: RenderedService,
  all: ReadonlyMap<string, { module: AnyModule; rendered: RenderedService }>,
  resourceOverride?: { memory?: string | undefined; cpus?: string | undefined },
): Record<string, unknown> {
  const service: Record<string, unknown> = {
    image: rendered.image,
    restart: rendered.restart,
    logging: {
      driver: 'json-file',
      options: { 'max-size': '10m', 'max-file': '3' },
    },
  }

  const dependsOn = dependencies(module, all)
  if (dependsOn) service['depends_on'] = dependsOn

  if (rendered.command) service['command'] = [...rendered.command]

  if (rendered.environment && Object.keys(rendered.environment).length > 0) {
    service['environment'] = { ...rendered.environment }
  }

  if (rendered.volumes && rendered.volumes.length > 0) {
    service['volumes'] = rendered.volumes.map(
      (v) => `${v.volume}:${v.path}${v.readOnly ? ':ro' : ''}`,
    )
  }

  if (rendered.hostNetwork) {
    service['network_mode'] = 'host'
  } else {
    service['networks'] = [NETWORK_NAME]
    if (rendered.ports && rendered.ports.length > 0) {
      service['ports'] = rendered.ports.map((p) => `${p.host}:${p.hostPort}:${p.containerPort}`)
    }
  }

  if (rendered.healthcheck) service['healthcheck'] = healthcheck(rendered.healthcheck)

  service['deploy'] = {
    resources: {
      limits: {
        cpus: resourceOverride?.cpus || module.cost.cpus,
        memory: resourceOverride?.memory || module.cost.memory,
      },
    },
  }

  return service
}

/**
 * Wait for health where the dependency reports it, and merely for start where
 * it does not.
 *
 * The distinction is not cosmetic: `service_healthy` against a service that
 * declares no healthcheck is an error compose refuses to run, so this reads
 * what the dependency actually rendered rather than assuming every module has
 * one. Adding a module without a healthcheck therefore degrades the wait
 * instead of breaking the file.
 */
function dependencies(
  module: AnyModule,
  all: ReadonlyMap<string, { module: AnyModule; rendered: RenderedService }>,
): Record<string, { condition: string }> | undefined {
  const present = module.requires.filter((id) => all.has(id))
  if (present.length === 0) return undefined

  return Object.fromEntries(
    present.map((id) => {
      const healthy = all.get(id)?.rendered.healthcheck !== undefined
      return [id, { condition: healthy ? 'service_healthy' : 'service_started' }]
    }),
  )
}

function healthcheck(check: HealthCheck): Record<string, unknown> {
  const out: Record<string, unknown> = { test: [...check.test] }
  if (check.interval) out['interval'] = check.interval
  if (check.timeout) out['timeout'] = check.timeout
  if (check.retries !== undefined) out['retries'] = check.retries
  if (check.startPeriod) out['start_period'] = check.startPeriod
  return out
}

